[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\n/home/yuki)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x5U\0\0\x2\xe7\0\0\0\0\0\0\0\0\0\0\x5U\0\0\x2\xff\0\0\0\0\x2\0\0\0\x5V\0\0\0\0\0\0\0\x16\0\0\x5U\0\0\x2\xe7)

[FullScreen]
pos=@Point(283 704)
screen=@Rect(0 0 1366 768)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(1366 650)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/yuki/Videos/Otakudesu.net_IseShku_720p/Otakudesu.net_IseShku--12_End_720p.mp4, file:///home/yuki/Videos/Otakudesu.net_IseShku_720p/Otakudesu.net_IseShku--11_720p.mp4, file:///home/yuki/Videos/Otakudesu.net_IseShku_720p/Otakudesu.net_IseShku--10_720p.mp4, file:///home/yuki/Videos/Otakudesu.net_IseShku_720p/Otakudesu.net_IseShku--09_720p.mp4, file:///home/yuki/Videos/Otakudesu.net_IseShku_720p/Otakudesu.net_IseShku--08_720p.mp4, file:///home/yuki/Videos/Otakudesu.net_IseShku_720p/Otakudesu.net_IseShku--07_720p.mp4, file:///home/yuki/Videos/Otakudesu.net_IseShku_720p/Otakudesu.net_IseShku--06_720p.mp4, file:///home/yuki/Videos/Otakudesu.net_IseShku_720p/Otakudesu.net_IseShku--05_720p.mp4, file:///home/yuki/Videos/Otakudesu.net_IseShku_720p/Otakudesu.net_IseShku--04_720p.mp4
times=0, 1346980, 0, 0, 0, 0, 0, 0, 0
