# Blur settings
blur-method = "dual_kawase";
blur-strength = 7;  # Sesuaikan kekuatan blur (0 untuk tidak ada blur, semakin besar semakin buram)

# Transparansi dan blur window tertentu
opacity-rule = [
    "90:class_g = 'kitty'"
];

# Fokus pada blur
wintypes:
{
    tooltip = { blur-background = true; };
    dock = { blur-background = true; };
    dnd = { blur-background = true; };
    normal = { blur-background = true; };
};

# Umum
backend = "glx";  # Untuk blur, backend "glx" juga bisa digunakan

