music_directory         "/home/yuki/Music"
playlist_directory       "/home/yuki/.config/mpd/playlists"
db_file                        "/home/yuki/.config/mpd/tag_cache"
log_file                       "/home/yuki/.config/mpd/mpd.log"
pid_file                       "/home/yuki/.config/mpd/mpd.pid"
state_file                     "/home/yuki/.config/mpd/mpdstate"
sticker_file                  "/home/yuki/.config/mpd/sticker.sql"

bind_to_address "0.0.0.0"

auto_update "yes"
audio_output {
	type "pulse"
		name "Pulse Audio"
}
audio_output {
	type "fifo"
		name "FIFO"
		path "/tmp/mpd.fifo"
		format "44100:16:2"
}
