[window]
padding.x = 30 
padding.y = 25 
opacity = 1.0

[font]
normal.family = "Iosevka Nerd Font"
normal.style = "Medium"
bold.family = "Iosevka Nerd Font"
bold.style = "Bold"
italic.family = "Iosevka Nerd Font"
italic.style = "Italic"

size= 9.5

[colors.primary]
background = '#191724'



